// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\untitled1\Subsystem.v
// Created: 2025-10-15 17:24:26
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: untitled1/Subsystem
// Hierarchy Level: 0
// Model version: 1.10
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] In1;  // single
  output  ce_out;
  output  [31:0] Out1;  // single


  wire [31:0] Exp_out1;  // ufix32


  nfp_exp_single u_nfp_exp_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in(In1),  // single
                                 .nfp_out(Exp_out1)  // single
                                 );

  assign Out1 = Exp_out1;

  assign ce_out = clk_enable;

endmodule  // Subsystem